kind: Service
apiVersion: v1
metadata:
  name: windows-exporter
  labels:
    name: windows-exporter
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9182
      targetPort: 9182
    - name: wicd-metrics
      protocol: TCP
      port: 9183
      targetPort: 9183
