apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: windows-instance-config-daemon
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
